# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a156aa8b15be4e788a25fa94d74ffe6176b7559ca14fcb94cc27fe9b9892f9a2d0f1dc4099122b70e46a767e20ed2a664969782c9d51916945eac5bec44abde

test:
  secret_key_base: fa50db7a4945ca00399cd1f487ebc7a17182e06555f9502846f9f7fa144ca52f22b5be3cb2c6d72bd502998606213a3218887a4115a091912c82483c1b5df9ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
